{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/Molinos2/Pages/FullScreen/HeaderFullScreen.page",
	"ModalPage": true,
	"ModalPageFullscreen": true,
	"NavigationType": "Inner",
	"Transition": {
		"Curve": "EaseOut"
	}
}