{
	"_Type": "Action.Type.Message",
	"Message": "$(L,ConfirmDelete)",
	"OKCaption": "$(L,YesCaption)",
	"CancelCaption": "$(L,NoCaption)",
	"OnOK": "/Molinos2/Actions/SalesOrderHeaders/SalesOrderHeaders_DeleteEntity.action"
}