{
	"_Type": "Action.Type.Message",
	"Message": "$(L,ConfirmDelete)",
	"OKCaption": "$(L,YesCaption)",
	"OnOK": "/Molinos2/Actions/Products/Products_DeleteEntity.action",
	"CancelCaption": "$(L,NoCaption)"
}